💄 128 - pdf feedback
icgc-argo/dac-ui pull request #192
Opened 2021-07-08 20:48 UTC by anncatton

2021-07-08 21:41 UTC, ciaranschutte commented on components/pages/Applications/PDF/StaticEthics.tsx
> +    ethicsRequiredPresent && !data?.sections.ethicsLetter.declaredAsRequired;
@anncatton  I'm inclined to go with something like `areEthicsRequired = ethicsRequiredPresent && data?.sections.ethicsLetter.declaredAsRequired`

Otherwise you're passing `ethicsRequiredFalse` into props requiring booleans, making the logic a little confusing to follow

2021-07-08 21:42 UTC, ciaranschutte commented on components/pages/Applications/PDF/StaticEthics.tsx
> +        {ethicsRequiredTrue && (
can probably just do one conditional here by wrapping in a fragment `<></>`

2021-07-08 21:43 UTC, ciaranschutte requested changes
two points to have a look at. looks really good

2021-07-08 22:39 UTC, anncatton commented on components/pages/Applications/PDF/StaticEthics.tsx
> +        {ethicsRequiredTrue && (
I just made the whole `View` conditional.

2021-07-08 22:39 UTC, caravinci commented on components/pages/Applications/PDF/StaticEthics.tsx
> +    ethicsRequiredPresent && !data?.sections.ethicsLetter.declaredAsRequired;
Ditto ☝️ ...
Maybe even simpler: const ethicsRequired = !!data?.sections.ethicsLetter.declaredAsRequired;?

2021-07-08 22:40 UTC, anncatton commented on components/pages/Applications/PDF/StaticEthics.tsx
> +    ethicsRequiredPresent && !data?.sections.ethicsLetter.declaredAsRequired;
the issue here is that i need to differentiate between a `null` value (nothing is checked) and a deliberate `true` or `false`. But i see what @ciaranschutte means by the logic being confusing

2021-07-08 23:22 UTC, caravinci commented on components/pages/Applications/PDF/Table.tsx
> +                ...(data.length && { borderBottom: 0 }),
```suggestion
                ...(data.length > 0 && { borderBottom: 0 }),
```

2021-07-09 01:40 UTC, ciaranschutte approved these changes

2021-07-09 14:15 UTC, merged