Feat/#59 sign submit feedback
icgc-argo/dac-ui pull request #225
Opened 2021-07-19 13:43 UTC by ciaranschutte

2021-07-19 20:25 UTC, caravinci approved these changes
LGTM 👍 
didn't test locally

2021-07-21 05:14 UTC, ciaranschutte commented
@caravinci please git another quick look. changed the handling slightly. 
removed the local `selectedFile` state to just use props from above

2021-07-21 12:32 UTC, caravinci requested changes
Mostly just to double check not undoing Ann's removal of IT Agreements

2021-07-21 12:32 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Forms/Collaborators.tsx
> +  console.log('localState', localState);
```suggestion
```

2021-07-21 12:32 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Forms/types.ts
> +export type FormSectionValidationState_ITAgreements = FormSectionValidationState_SectionsGenericType<{
This section was removed, if I recall correctly.
There may be some version conflicts in this file that are worth double checking just in case I'm not wrong.

2021-07-21 13:35 UTC, caravinci approved these changes

2021-07-21 13:36 UTC, merged