Feat/#490 dashboard card for access paused
icgc-argo/dac-ui pull request #616
Opened 2022-07-05 16:04 UTC by daniel-cy-lu

2022-07-05 16:51 UTC, caravinci requested changes
Great work thus far! Left a couple comments to make it even better 🙏

2022-07-05 16:51 UTC, caravinci commented on components/ApplicationProgressBar/index.tsx
> +
```suggestion
```

No need for that additional empty line

2022-07-05 16:51 UTC, caravinci commented on components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
>        [
unrelated to your PR, but this line is missing a `return` to match the other cases.
May be a good thing to fix while at it.
```suggestion
      return [
```

2022-07-05 16:51 UTC, caravinci commented on components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
> +        ];
Indentation is off on these changes, when compared to the existing code.
You may want to double check your `prettier` plugin still on and functional?

2022-07-05 16:51 UTC, caravinci commented on components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
> +    ;
It may just be me (others may disagree) but I find this `A &&  B || C` less than straightforward to reason with.
Could I suggest adding parentheses where appropriate, to make it more readable?

2022-07-05 19:23 UTC, daniel-cy-lu commented on components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
>        [
`return` added in line 98 to make the case work properly.

2022-07-05 19:27 UTC, daniel-cy-lu commented on components/pages/Applications/Dashboard/Applications/InProgress/ButtonGroup.tsx
> +        ];
indentation is aligned for PAUSED case.

2022-07-05 19:35 UTC, daniel-cy-lu commented
Thanks for the comments, Justin. I've made changes to each of the commands you made!

2022-07-05 22:22 UTC, caravinci approved these changes
LGTM :shipit:

2022-07-06 14:17 UTC, anncatton approved these changes
Just a couple little comments, but otherwise looks good! Great work @daniel-cy-lu

2022-07-06 14:22 UTC, anncatton commented
Also one more small comment, don't forget to add a description to your PR! This one is pretty straightforward but it's a nice habit to get into 🙂 . You can add points for changes you made, something like 
`- Adds PAUSED state. `
`- adds status bar section and warning message for paused applications`

2022-07-06 16:19 UTC, daniel-cy-lu commented on components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
>    const expiryDate =
update the variable name from `expiryDate` to `statusDate` to reflect the purpose better

2022-07-06 16:22 UTC, daniel-cy-lu commented on components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
> +    ;
the condition is now read like `C || (A&&B)`. What is prettier? :)

2022-07-06 16:30 UTC, daniel-cy-lu commented
- Add `PAUSED` state to `ApplicationState`
- Add 1. button 2. status text 3. progress bar 4. status date warning, that are specific to the `PAUSED` state

2022-07-06 16:31 UTC, daniel-cy-lu commented
Thanks Ann! Next time I will put the PR comments on the top of the PR haha!

2022-07-06 17:27 UTC, anncatton commented
> Thanks Ann! Next time I will put the PR comments on the top of the PR haha!

You still can 😉

2022-07-06 18:35 UTC, anncatton commented on components/pages/Applications/Dashboard/Applications/InProgress/index.tsx
> +    ;
prettier is something that will change your life! if you use vscode you can install this https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2022-07-07 13:40 UTC, caravinci commented
Much better, after enabling `prettier`! 🎉

2022-07-11 15:20 UTC, merged