Feat/#484 attestation application state 45 days prior to attestation date
icgc-argo/dac-ui pull request #620
Opened 2022-07-19 18:43 UTC by daniel-cy-lu

2022-07-19 19:09 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +                Annual Attestation is required by July 28, 2022 or access will be paused
Is this date supposed to be fixed/hardcoded for every application?

2022-07-19 19:17 UTC, caravinci requested changes
Other than that hardcoded date comment, the changes generally LGTM :+1:
Will defer to @anncatton for feature-specific feedback + approval.

2022-07-19 19:35 UTC, caravinci approved these changes

2022-07-19 19:39 UTC, caravinci reviewed
Suggestion, not required:
You could make that date line simpler if you make `attestationByUtc` default to empty string when missing.

2022-07-19 19:39 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +                  new Date(attestationByUtc || ''),
```suggestion
                  new Date(attestationByUtc),
```

2022-07-19 19:39 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +  attestationByUtc,
```suggestion
  attestationByUtc = '',
```

2022-07-19 19:40 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Header/index.tsx
> +        date: format(new Date(attestationByUtc || ''), DATE_TEXT_FORMAT),
which could also be done here

2022-07-19 19:44 UTC, daniel-cy-lu commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +  attestationByUtc,
Got it! like what we did when we were coming up with the mock data.

2022-07-19 19:44 UTC, daniel-cy-lu commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +                  new Date(attestationByUtc || ''),
Good idea. I will make both of your suggested changes.

2022-07-19 19:46 UTC, daniel-cy-lu commented on components/pages/Applications/ApplicationForm/Header/index.tsx
> +        date: format(new Date(attestationByUtc || ''), DATE_TEXT_FORMAT),
I will make this change as well!

2022-07-19 20:05 UTC, caravinci commented on components/pages/Applications/ApplicationForm/Header/index.tsx
> +        date: format(new Date(closedAtUtc || expiresAtUtc), DATE_TEXT_FORMAT),
+Going above and beyond! 💫

2022-07-22 12:24 UTC, anncatton approved these changes
Great work @daniel-cy-lu ! We can just check that one comment I made about paused state that's going to come up in #486

2022-07-22 12:24 UTC, anncatton commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +        {/* forward thinking: requiresAttestation is also true for PAUSED state, therefore we want to make sure application is in APPROVED state */}
i think the banner is the same when the app is in paused state so we may not need this check...however i can check with @kcullion 🙂 
but still a good thought, and thanks for the helpful comment!

2022-07-22 12:45 UTC, kcullion commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +        {/* forward thinking: requiresAttestation is also true for PAUSED state, therefore we want to make sure application is in APPROVED state */}
yes the banner remains on the application when the access is paused...and the application is locked. mockup: https://zpl.io/bloeKXP

2022-07-25 14:19 UTC, daniel-cy-lu commented on components/pages/Applications/ApplicationForm/Forms/index.tsx
> +        {/* forward thinking: requiresAttestation is also true for PAUSED state, therefore we want to make sure application is in APPROVED state */}
The same banner is used in '45 days period' and in 'Paused' state. The warning banner now appears regardless of the state. It appears whenever the application needs attestation to be done.

2022-07-25 14:20 UTC, merged